---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: web-resource
spec:
  hard:
    cpu: 500m
    memory: 256Mi
    pods: 2
    resourcequotas: 1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx-default.conf: |
    server {
      listen  80;
      server_name localhost;
      
      location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
      }
    }
---
apiVersion: v1
kind: Pod
metadata:
  name: website
  labels:
     name: website
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      resources:
         requests:
            cpu: 100m
            memory: 128Mi
      volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
        - name: web-volume
          mountPath: /usr/share/nginx/html
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-conf
        items:
          - key: nginx-default.conf
            path: default.conf
     - name: web-volume
       persistentVolumeClaim:
         - claimName: pvc-web
---
apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    name: website
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
      targetPort: 80
      protocol: TCP
---
apiVersion: v1
kind: Route
metadata:
  name: website
spec:
  host: web.openshiftdemo.local
  to:
    kind: Service
    name: website
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-web
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  nfs:
    server: 192.168.99.1
    path: /mnt/nfsvol
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
    volumeName: pv-web
